---
title: "distribution/regression"
author: "Jieqi Tu"
date: "2/1/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Import datafile
```{r import data}
biopsy.grade = readxl::read_excel("./data/GG_AP_ClinicalOutcomes_Biostats.xlsx", sheet = "Biopsy Grade Group")
adverse.pathology = readxl::read_excel("./data/GG_AP_ClinicalOutcomes_Biostats.xlsx", sheet = "Adverse Pathology")
serum.geneglobe = readxl::read_excel("./data/Serum_SerumEV_GeneGlobeRQ_CT35.xlsx", sheet = "Serum_GeneGlobeRQ_CT35")
EV.geneglobe = readxl::read_excel("./data/Serum_SerumEV_GeneGlobeRQ_CT35.xlsx", sheet = "EV_GeneGlobeRQ_CT35")
```

## Tidy Data
```{r tidy data}
# change format from wide to long
# serum
new = t(serum.geneglobe)
name_tmp <- new[1,]
new <- new[-1,]
new <- apply(new,1,as.numeric) %>% t()
colnames(new) <- (name_tmp)
serum.geneglobe.new = new %>% as.data.frame()
serum.geneglobe.new = rownames_to_column(serum.geneglobe.new)
colnames(serum.geneglobe.new)[1] = "Patient ID"

# EV
new = t(EV.geneglobe)
name_tmp <- new[1,]
new <- new[-1,]
new <- apply(new,1,as.numeric) %>% t()
colnames(new) <- (name_tmp)
EV.geneglobe.new = new %>% as.data.frame()
EV.geneglobe.new = rownames_to_column(EV.geneglobe.new)
colnames(EV.geneglobe.new)[1] = "Patient ID"
```

## Checking distribution for each microRNA
```{r distribution}
# checking distribution for serum
normality.test.serum = data.frame(
  micrioRNA = colnames(serum.geneglobe.new[-1]),
  p.value = numeric(length(micrioRNA))
)

for (i in 1:61) {
  test = shapiro.test(serum.geneglobe.new[,i+1])
  normality.test.serum$p.value[i] = test$p.value
}

# checking distribution for EV
normality.test.EV = data.frame(
  micrioRNA = colnames(EV.geneglobe.new[-1]),
  p.value = numeric(length(micrioRNA))
)

for (i in 1:61) {
  test = shapiro.test(EV.geneglobe.new[,i+1])
  normality.test.EV$p.value[i] = test$p.value
}

# Results display
normality.test.serum
normality.test.EV
```

Conclusion: None of the microRNA has the normal distribution. 

## Univariate GLM fitting
```{r univariate GLM}
# datafile combine
# left join for grade groups
serum.grade = left_join(serum.geneglobe.new, biopsy.grade, by = "Patient ID")
EV.grade = left_join(EV.geneglobe.new, biopsy.grade, by = "Patient ID")

# left join for adverse pathology
serum.all = left_join(serum.grade, adverse.pathology, by = "Patient ID")
EV.all = left_join(EV.grade, adverse.pathology, by = "Patient ID")
```

