---
title: "Analysis 2/6"
author: "Jieqi Tu"
date: "2/6/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

## Import data
```{r data import}
biopsy.grade = readxl::read_excel("./data/GG_AP_ClinicalOutcomes_Biostats.xlsx", sheet = "Biopsy Grade Group")
adverse.pathology = readxl::read_excel("./data/GG_AP_ClinicalOutcomes_Biostats.xlsx", sheet = "Adverse Pathology")
serum.globalCTMean = readxl::read_excel("./data/Serum_AdjustedRQ_CT35_BioStats.xlsx", sheet = "GlobalCTMean RQ")
serum.geNorm = readxl::read_excel("./data/Serum_AdjustedRQ_CT35_BioStats.xlsx", sheet = "geNorm RQ")
serum.NormFinder = readxl::read_excel("./data/Serum_AdjustedRQ_CT35_BioStats.xlsx", sheet = "geNorm NormFinder RQ")
EV.globalCTMean = readxl::read_excel("./data/SerumEV_AdjustedRQ_CT35_BioStats.xlsx", sheet = "GlobalCTMean RQ")
EV.geNorm = readxl::read_excel("./data/SerumEV_AdjustedRQ_CT35_BioStats.xlsx", sheet = "geNorm RQ")
EV.NormFinder = readxl::read_excel("./data/SerumEV_AdjustedRQ_CT35_BioStats.xlsx", sheet = "geNorm NormFinder RQ")
serum.geneglobe = readxl::read_excel("./data/Serum_SerumEV_GeneGlobeRQ_CT35.xlsx", sheet = "Serum_GeneGlobeRQ_CT35")
EV.geneglobe = readxl::read_excel("./data/Serum_SerumEV_GeneGlobeRQ_CT35.xlsx", sheet = "EV_GeneGlobeRQ_CT35")
```

## Tidy data
```{r tidy data1}
library(tidyverse)
# Serum global CT mean
new = t(serum.globalCTMean)
name_tmp <- new[1,]
new <- new[-1,]
new <- apply(new,1,as.numeric) %>% t()
colnames(new) <- (name_tmp)
serum.globalCTMean.new = new %>% as.data.frame()
serum.globalCTMean.new = rownames_to_column(serum.globalCTMean.new)
colnames(serum.globalCTMean.new)[1] = "Patient ID"

# Serum geNorm
new = t(serum.geNorm)
name_tmp <- new[1,]
new <- new[-1,]
new <- apply(new,1,as.numeric) %>% t()
colnames(new) <- (name_tmp)
serum.geNorm.new = new %>% as.data.frame()
serum.geNorm.new = rownames_to_column(serum.geNorm.new)
colnames(serum.globalCTMean.new)[1] = "Patient ID"

# Serum geNorm Finder
new = t(serum.NormFinder)
name_tmp <- new[1,]
new <- new[-1,]
new <- apply(new,1,as.numeric) %>% t()
colnames(new) <- (name_tmp)
serum.NormFinder.new = new %>% as.data.frame()
serum.NormFinder.new = rownames_to_column(serum.NormFinder.new)
colnames(serum.NormFinder.new)[1] = "Patient ID"

# EV global CT Mean
new = t(EV.globalCTMean)
name_tmp <- new[1,]
new <- new[-1,]
new <- apply(new,1,as.numeric) %>% t()
colnames(new) <- (name_tmp)
EV.globalCTMean.new = new %>% as.data.frame()
EV.globalCTMean.new = rownames_to_column(EV.globalCTMean.new)
colnames(EV.globalCTMean.new)[1] = "Patient ID"

# EV geNorm
new = t(EV.geNorm)
name_tmp <- new[1,]
new <- new[-1,]
new <- apply(new,1,as.numeric) %>% t()
colnames(new) <- (name_tmp)
EV.geNorm.new = new %>% as.data.frame()
EV.geNorm.new = rownames_to_column(EV.geNorm.new)
colnames(EV.geNorm.new)[1] = "Patient ID"

# EV geNorm NormFinder
new = t(EV.NormFinder)
name_tmp <- new[1,]
new <- new[-1,]
new <- apply(new,1,as.numeric) %>% t()
colnames(new) <- (name_tmp)
EV.NormFinder.new = new %>% as.data.frame()
EV.NormFinder.new = rownames_to_column(EV.NormFinder.new)
colnames(EV.NormFinder.new)[1] = "Patient ID"


# Adverse pathology
adverse.pathology$`Adverse Pathology` = ifelse(adverse.pathology$`Adverse Pathology` == "99", NA, adverse.pathology$`Adverse Pathology`)
```
```{r tidy data}
# change format from wide to long
# serum
new = t(serum.geneglobe)
name_tmp <- new[1,]
new <- new[-1,]
new <- apply(new,1,as.numeric) %>% t()
colnames(new) <- (name_tmp)
serum.geneglobe.new = new %>% as.data.frame()
serum.geneglobe.new = rownames_to_column(serum.geneglobe.new)
colnames(serum.geneglobe.new)[1] = "Patient ID"

# EV
new = t(EV.geneglobe)
name_tmp <- new[1,]
new <- new[-1,]
new <- apply(new,1,as.numeric) %>% t()
colnames(new) <- (name_tmp)
EV.geneglobe.new = new %>% as.data.frame()
EV.geneglobe.new = rownames_to_column(EV.geneglobe.new)
colnames(EV.geneglobe.new)[1] = "Patient ID"

# Adverse pathology
adverse.pathology$`Adverse Pathology` = ifelse(adverse.pathology$`Adverse Pathology` == "99", NA, adverse.pathology$`Adverse Pathology`)
```

## Distribution checking
```{r distribution checking}
# serum global ct mean
normality.test.serum.CTMean = data.frame(
  microRNA = colnames(serum.globalCTMean.new[-1]),
  p.value = numeric(61),
  method = "Global CTMean"
)

for (i in 1:61) {
  test = shapiro.test(serum.globalCTMean.new[,i+1])
  normality.test.serum.CTMean$p.value[i] = test$p.value
}

# serum geNorm
normality.test.serum.geNorm = data.frame(
  microRNA = colnames(serum.geNorm.new[-1]),
  p.value = numeric(61),
  method = "geNorm"
)

for (i in 1:61) {
  test = shapiro.test(serum.geNorm.new[,i+1])
  normality.test.serum.geNorm$p.value[i] = test$p.value
}

# serum geNorm NormFinder
normality.test.serum.NormFinder = data.frame(
  microRNA = colnames(serum.NormFinder.new[-1]),
  p.value = numeric(61),
  method = "NormFinder"
)

for (i in 1:61) {
  test = shapiro.test(serum.NormFinder.new[,i+1])
  normality.test.serum.NormFinder$p.value[i] = test$p.value
}

# EV global CT Mean
normality.test.EV.CTMean = data.frame(
  microRNA = colnames(EV.globalCTMean.new[-1]),
  p.value = numeric(61),
  method = "Global CTMean"
)

for (i in 1:61) {
  test = shapiro.test(EV.globalCTMean.new[,i+1])
  normality.test.EV.CTMean$p.value[i] = test$p.value
}

# EV geNorm
normality.test.EV.geNorm = data.frame(
  microRNA = colnames(EV.geNorm.new[-1]),
  p.value = numeric(61),
  method = "geNorm"
)

for (i in 1:61) {
  test = shapiro.test(EV.geNorm.new[,i+1])
  normality.test.EV.geNorm$p.value[i] = test$p.value
}

EV.NormFinder.new2 = EV.NormFinder.new[,-7]
# EV NormFinder
normality.test.EV.NormFinder = data.frame(
  microRNA = colnames(EV.NormFinder.new2[-1]),
  p.value = numeric(60),
  method = "NormFinder"
)

for (i in 1:60) {
  test = shapiro.test(EV.NormFinder.new2[,i+1])
  normality.test.EV.NormFinder$p.value[i] = test$p.value
}

normality.test.serum = data.frame(
  microRNA = colnames(serum.geneglobe.new[-1]),
  p.value = numeric(61),
  method = "Gene Globe"
)

for (i in 1:61) {
  test = shapiro.test(serum.geneglobe.new[,i+1])
  normality.test.serum$p.value[i] = test$p.value
}

# checking distribution for EV
normality.test.EV = data.frame(
  microRNA = colnames(EV.geneglobe.new[-1]),
  p.value = numeric(61),
  method = "Gene Globe"
)

for (i in 1:61) {
  test = shapiro.test(EV.geneglobe.new[,i+1])
  normality.test.EV$p.value[i] = test$p.value
}

normality.result.serum = rbind(normality.test.serum, normality.test.serum.CTMean, normality.test.serum.geNorm, normality.test.serum.NormFinder)
normality.result.EV = rbind(normality.test.EV, normality.test.EV.CTMean, normality.test.EV.geNorm, normality.test.EV.NormFinder)
normality.result.serum %>% filter(p.value >= 0.05)
normality.result.EV %>% filter(p.value >= 0.05)
library(openxlsx)
write.xlsx(list(normality.result.serum, normality.result.EV), file = "Normality test results.xlsx")
```

## Univariate GLM fitting
```{r data fine manipulation}
# datafile combine
# left join for grade groups
serum.grade.original = left_join(serum.geneglobe.new, biopsy.grade, by = "Patient ID")
EV.grade.original = left_join(EV.geneglobe.new, biopsy.grade, by = "Patient ID")

# left join for adverse pathology
serum.all.original = left_join(serum.grade.original, adverse.pathology, by = "Patient ID")
EV.all.original = left_join(EV.grade.original, adverse.pathology, by = "Patient ID")
```

```{r GLM fitting}
grade.serum.result = data.frame(
  microRNA = colnames(serum.geneglobe.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
  
)
for (i in 1:61) {
  model = glm(formula = serum.all.original$`Biopsy Grade Group`~serum.all.original[,i+1])
  result = summary(model)
  grade.serum.result$coefficient.estimates[i] = result$coefficients[2,1]
  grade.serum.result$standard.deviation[i] = result$coefficients[2,2]
  grade.serum.result$p.value[i] = result$coefficients[2,4]
}

grade.EV.result = data.frame(
  microRNA = colnames(EV.geneglobe.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)

for (i in 1:61) {
  model = glm(formula = EV.all.original$`Biopsy Grade Group`~EV.all.original[,i+1])
  result = summary(model)
  grade.EV.result$coefficient.estimates[i] = result$coefficients[2,1]
  grade.EV.result$standard.deviation = result$coefficients[2,2]
  grade.EV.result$p.value[i] = result$coefficients[2,4]
}

# Display result
# univariate GLM
adverse.serum.result = data.frame(
  microRNA = colnames(serum.geneglobe.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = serum.all.original$`Adverse Pathology`~serum.all.original[,i+1], family = "binomial")
  result = summary(model)
  adverse.serum.result$coefficient.estimates[i] = result$coefficients[2,1]
  adverse.serum.result$standard.deviation[i] = result$coefficients[2,2]
  adverse.serum.result$p.value[i] = result$coefficients[2,4]
}

adverse.EV.result = data.frame(
  microRNA = colnames(EV.geneglobe.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)

for (i in 1:61) {
  model = glm(formula = EV.all.original$`Adverse Pathology`~EV.all.original[,i+1], family = "binomial")
  result = summary(model)
  adverse.EV.result$coefficient.estimates[i] = result$coefficients[2,1]
  adverse.EV.result$standard.deviation[i] = result$coefficients[2,2]
  adverse.EV.result$p.value[i] = result$coefficients[2,4]
}

# Display result
adverse.EV.result = grade.serum.result[order(grade.serum.result$p.value),]
grade.EV.result = grade.EV.result[order(grade.EV.result$p.value),]

# Serum global CTMean
grade.serum.CTMean.result = data.frame(
  microRNA = colnames(serum.globalCTMean.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = serum.all.original$`Biopsy Grade Group`~serum.globalCTMean.new[,i+1])
  result = summary(model)
  grade.serum.CTMean.result$coefficient.estimates[i] = result$coefficients[2,1]
  grade.serum.CTMean.result$standard.deviation[i] = result$coefficients[2,2]
  grade.serum.CTMean.result$p.value[i] = result$coefficients[2,4]
}

grade.serum.CTMean.result = grade.serum.CTMean.result[order(grade.serum.CTMean.result$p.value),]

# Serum geNorm
grade.serum.geNorm.result = data.frame(
  microRNA = colnames(serum.geNorm.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = serum.all.original$`Biopsy Grade Group`~serum.geNorm.new[,i+1])
  result = summary(model)
  grade.serum.geNorm.result$coefficient.estimates[i] = result$coefficients[2,1]
  grade.serum.geNorm.result$standard.deviation[i] = result$coefficients[2,2]
  grade.serum.geNorm.result$p.value[i] = result$coefficients[2,4]
}

grade.serum.geNorm.result = grade.serum.geNorm.result[order(grade.serum.geNorm.result$p.value),]

# Serum NormFinder
grade.serum.NormFinder.result = data.frame(
  microRNA = colnames(serum.NormFinder.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = serum.all.original$`Biopsy Grade Group`~serum.NormFinder.new[,i+1])
  result = summary(model)
  grade.serum.NormFinder.result$coefficient.estimates[i] = result$coefficients[2,1]
  grade.serum.NormFinder.result$standard.deviation[i] = result$coefficients[2,2]
  grade.serum.NormFinder.result$p.value[i] = result$coefficients[2,4]
}

grade.serum.NormFinder.result = grade.serum.NormFinder.result[order(grade.serum.NormFinder.result$p.value),]

EV.grade.CTMean = left_join(EV.globalCTMean.new,biopsy.grade, by = "Patient ID")

# EV global CT Mean
grade.EV.CTMean.result = data.frame(
  microRNA = colnames(EV.globalCTMean.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = EV.grade.CTMean$`Biopsy Grade Group`~ EV.globalCTMean.new[,i+1])
  result = summary(model)
  grade.EV.CTMean.result$coefficient.estimates[i] = result$coefficients[2,1]
  grade.EV.CTMean.result$standard.deviation[i] = result$coefficients[2,2]
  grade.EV.CTMean.result$p.value[i] = result$coefficients[2,4]
}

grade.EV.CTMean.result = grade.EV.CTMean.result[order(grade.EV.CTMean.result$p.value),]

# EV geNorm
grade.EV.geNorm.result = data.frame(
  microRNA = colnames(EV.geNorm.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = EV.grade.CTMean$`Biopsy Grade Group`~ EV.geNorm.new[,i+1])
  result = summary(model)
  grade.EV.geNorm.result$coefficient.estimates[i] = result$coefficients[2,1]
  grade.EV.geNorm.result$standard.deviation[i] = result$coefficients[2,2]
  grade.EV.geNorm.result$p.value[i] = result$coefficients[2,4]
}

grade.EV.geNorm.result = grade.EV.geNorm.result[order(grade.EV.geNorm.result$p.value),]


# EV Norm Finder
grade.EV.NormFinder.result = data.frame(
  microRNA = colnames(EV.NormFinder.new2)[-1],
  coefficient.estimates = numeric(60),
  standard.deviation = numeric(60),
  p.value = numeric(60)
)
for (i in 1:60) {
  model = glm(formula = EV.grade.CTMean$`Biopsy Grade Group`~ EV.NormFinder.new2[,i+1])
  result = summary(model)
  grade.EV.NormFinder.result$coefficient.estimates[i] = result$coefficients[2,1]
  grade.EV.NormFinder.result$standard.deviation[i] = result$coefficients[2,2]
  grade.EV.NormFinder.result$p.value[i] = result$coefficients[2,4]
}

grade.EV.NormFinder.result = grade.EV.NormFinder.result[order(grade.EV.NormFinder.result$p.value),]

# Collect the results
grade.serum.GLM.result = write.xlsx(list(grade.serum.result, grade.serum.CTMean.result, grade.serum.geNorm.result, grade.serum.NormFinder.result), file = "serumGLMresults.xlsx")
grade.EV.GLM.result = write.xlsx(list(grade.EV.result, grade.EV.CTMean.result, grade.EV.geNorm.result, grade.EV.NormFinder.result), file = "EVGLMresults.xlsx")
```

```{r AP GLM fitting}
# univariate GLM
adverse.serum.result = data.frame(
  microRNA = colnames(serum.geneglobe.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = serum.all.original$`Adverse Pathology`~serum.all.original[,i+1], family = "binomial")
  result = summary(model)
  adverse.serum.result$coefficient.estimates[i] = result$coefficients[2,1]
  adverse.serum.result$standard.deviation[i] = result$coefficients[2,2]
  adverse.serum.result$p.value[i] = result$coefficients[2,4]
}

adverse.EV.result = data.frame(
  microRNA = colnames(EV.geneglobe.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)

for (i in 1:61) {
  model = glm(formula = EV.all.original$`Adverse Pathology`~EV.all.original[,i+1], family = "binomial")
  result = summary(model)
  adverse.EV.result$coefficient.estimates[i] = result$coefficients[2,1]
  adverse.EV.result$standard.deviation[i] = result$coefficients[2,2]
  adverse.EV.result$p.value[i] = result$coefficients[2,4]
}

# Display result
adverse.serum.result = adverse.serum.result[order(adverse.serum.result$p.value),]
adverse.EV.result = adverse.EV.result[order(adverse.EV.result$p.value),]

# Serum global CTMean
adverse.serum.CTMean.result = data.frame(
  microRNA = colnames(serum.globalCTMean.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = serum.all.original$`Adverse Pathology`~serum.globalCTMean.new[,i+1], family = "binomial")
  result = summary(model)
  adverse.serum.CTMean.result$coefficient.estimates[i] = result$coefficients[2,1]
  adverse.serum.CTMean.result$standard.deviation[i] = result$coefficients[2,2]
  adverse.serum.CTMean.result$p.value[i] = result$coefficients[2,4]
}

adverse.serum.CTMean.result = adverse.serum.CTMean.result[order(adverse.serum.CTMean.result$p.value),]

# Serum geNorm
adverse.serum.geNorm.result = data.frame(
  microRNA = colnames(serum.geNorm.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = serum.all.original$`Adverse Pathology`~serum.geNorm.new[,i+1], family = "binomial")
  result = summary(model)
  adverse.serum.geNorm.result$coefficient.estimates[i] = result$coefficients[2,1]
  adverse.serum.geNorm.result$standard.deviation[i] = result$coefficients[2,2]
  adverse.serum.geNorm.result$p.value[i] = result$coefficients[2,4]
}

adverse.serum.geNorm.result = adverse.serum.geNorm.result[order(adverse.serum.geNorm.result$p.value),]

# Serum NormFinder
adverse.serum.NormFinder.result = data.frame(
  microRNA = colnames(serum.NormFinder.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = serum.all.original$`Adverse Pathology`~serum.NormFinder.new[,i+1], family = "binomial")
  result = summary(model)
  adverse.serum.NormFinder.result$coefficient.estimates[i] = result$coefficients[2,1]
  adverse.serum.NormFinder.result$standard.deviation[i] = result$coefficients[2,2]
  adverse.serum.NormFinder.result$p.value[i] = result$coefficients[2,4]
}

adverse.serum.NormFinder.result = adverse.serum.NormFinder.result[order(adverse.serum.NormFinder.result$p.value),]

EV.adverse.CTMean = left_join(EV.globalCTMean.new, adverse.pathology, by = "Patient ID")

# EV global CT Mean
adverse.EV.CTMean.result = data.frame(
  microRNA = colnames(EV.globalCTMean.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = EV.adverse.CTMean$`Adverse Pathology`~ EV.globalCTMean.new[,i+1], family = "binomial")
  result = summary(model)
  adverse.EV.CTMean.result$coefficient.estimates[i] = result$coefficients[2,1]
  adverse.EV.CTMean.result$standard.deviation[i] = result$coefficients[2,2]
  adverse.EV.CTMean.result$p.value[i] = result$coefficients[2,4]
}

adverse.EV.CTMean.result = adverse.EV.CTMean.result[order(adverse.EV.CTMean.result$p.value),]

# EV geNorm
adverse.EV.geNorm.result = data.frame(
  microRNA = colnames(EV.geNorm.new)[-1],
  coefficient.estimates = numeric(61),
  standard.deviation = numeric(61),
  p.value = numeric(61)
)
for (i in 1:61) {
  model = glm(formula = EV.adverse.CTMean$`Adverse Pathology`~ EV.geNorm.new[,i+1], family = "binomial")
  result = summary(model)
  adverse.EV.geNorm.result$coefficient.estimates[i] = result$coefficients[2,1]
  adverse.EV.geNorm.result$standard.deviation[i] = result$coefficients[2,4]
  adverse.EV.geNorm.result$p.value[i] = result$coefficients[2,4]
}

adverse.EV.geNorm.result = adverse.EV.geNorm.result[order(adverse.EV.geNorm.result$p.value),]


# EV Norm Finder
adverse.EV.NormFinder.result = data.frame(
  microRNA = colnames(EV.NormFinder.new2)[-1],
  coefficient.estimates = numeric(60),
  standard.deviation = numeric(60),
  p.value = numeric(60)
)
for (i in 1:60) {
  model = glm(formula = EV.adverse.CTMean$`Adverse Pathology`~ EV.NormFinder.new2[,i+1], family = "binomial")
  result = summary(model)
  adverse.EV.NormFinder.result$coefficient.estimates[i] = result$coefficients[2,1]
  adverse.EV.NormFinder.result$standard.deviation[i] = result$coefficients[2,2]
  adverse.EV.NormFinder.result$p.value[i] = result$coefficients[2,4]
}

adverse.EV.NormFinder.result = adverse.EV.NormFinder.result[order(adverse.EV.NormFinder.result$p.value),]

# Collect the results
adverse.serum.GLM.result = write.xlsx(list(adverse.serum.result, adverse.serum.CTMean.result, adverse.serum.geNorm.result, adverse.serum.NormFinder.result), file = "APserumGLMresults.xlsx")
adverse.EV.GLM.result = write.xlsx(list(adverse.EV.result, adverse.EV.CTMean.result, adverse.EV.geNorm.result, adverse.EV.NormFinder.result), file = "APEVGLMresults.xlsx")
```

## Variable selection
```{r variable selection1}
# get the significant results
grade.serum.result.significant = 
  grade.serum.result %>% filter(p.value <= 0.05)

grade.serum.result.significant

grade.EV.result.significant = 
  grade.EV.result %>% filter(p.value <= 0.05)

grade.EV.result.significant

# serum CT mean
grade.serum.CTMean.result.sigficant = 
  grade.serum.CTMean.result %>% filter(p.value <= 0.05)

grade.serum.CTMean.result.sigficant

# serum geNorm
grade.serum.geNorm.result.sigficant = 
  grade.serum.geNorm.result %>% filter(p.value <= 0.05)

grade.serum.geNorm.result.sigficant

# serum Norm Finder
grade.serum.NormFinder.result.sigficant = 
  grade.serum.NormFinder.result %>% filter(p.value <= 0.05)

grade.serum.NormFinder.result.sigficant 

# EV CT Mean
grade.EV.CTMean.result.sigficant = 
  grade.EV.CTMean.result %>% filter(p.value <= 0.05)

grade.EV.CTMean.result.sigficant

# EV geNorm
grade.EV.geNorm.result.sigficant = 
  grade.EV.geNorm.result %>% filter(p.value <= 0.05)

grade.EV.geNorm.result.sigficant

# EV Norm Finder
grade.EV.NormFinder.result.sigficant = 
  grade.EV.NormFinder.result %>% filter(p.value <= 0.05)

grade.EV.NormFinder.result.sigficant
```



```{r variable selection2}
# get the significant results
adverse.serum.result.significant = 
  adverse.serum.result %>% filter(p.value <= 0.05)

adverse.serum.result.significant

adverse.EV.result.significant = 
  adverse.EV.result %>% filter(p.value <= 0.05)

adverse.EV.result.significant

# serum CT mean
adverse.serum.CTMean.result.sigficant = 
  adverse.serum.CTMean.result %>% filter(p.value <= 0.05)

adverse.serum.CTMean.result.sigficant

# serum geNorm
adverse.serum.geNorm.result.sigficant = 
  adverse.serum.geNorm.result %>% filter(p.value <= 0.05)

adverse.serum.geNorm.result.sigficant

# serum Norm Finder
adverse.serum.NormFinder.result.sigficant = 
  adverse.serum.NormFinder.result %>% filter(p.value <= 0.05)

adverse.serum.NormFinder.result.sigficant 

# EV CT Mean
adverse.EV.CTMean.result.sigficant = 
  adverse.EV.CTMean.result %>% filter(p.value <= 0.05)

adverse.EV.CTMean.result.sigficant

# EV geNorm
adverse.EV.geNorm.result.sigficant = 
  adverse.EV.geNorm.result %>% filter(p.value <= 0.05)

adverse.EV.geNorm.result.sigficant

# EV Norm Finder
adverse.EV.NormFinder.result.sigficant = 
  adverse.EV.NormFinder.result %>% filter(p.value <= 0.05)

adverse.EV.NormFinder.result.sigficant
```

## Biopsy Grade selection
```{r selection3}
library(MASS)
fullmodel1 = glm(data = serum.all.original, formula = `Biopsy Grade Group`~`hsa-miR-1246`+`hsa-miR-214-3p`+`hsa-miR-301a-3p`)
serum.grade.final = stepAIC(object = fullmodel1, direction = "backward")

# serum CT Mean
fullmodel.serum.ctmean = glm(formula = serum.all.original$`Biopsy Grade Group`~ serum.globalCTMean.new$`hsa-miR-1246`+ serum.globalCTMean.new$`hsa-miR-363-3p`+ serum.globalCTMean.new$`hsa-miR-320a` + serum.globalCTMean.new$`hsa-miR-125b-5p` + serum.globalCTMean.new$`hsa-miR-27a-3p` + serum.globalCTMean.new$`hsa-miR-16-5p` + serum.globalCTMean.new$`hsa-let-7b-5p` + serum.globalCTMean.new$`hsa-miR-27b-3p` + serum.globalCTMean.new$`hsa-miR-29a-3p` + serum.globalCTMean.new$`hsa-miR-21-5p` + serum.globalCTMean.new$`hsa-miR-451a` + serum.globalCTMean.new$`hsa-miR-874-3p`)

step.serum.grade.CTMean = stepAIC(object = fullmodel.serum.ctmean, direction = "backward")

# serum geNorm
fullmodel.serum.geNorm = glm(formula = serum.all.original$`Biopsy Grade Group`~ serum.geNorm.new$`hsa-miR-1246`+ serum.geNorm.new$`hsa-miR-363-3p`+ serum.geNorm.new$`hsa-miR-320a` + serum.geNorm.new$`hsa-miR-125b-5p` + serum.geNorm.new$`hsa-miR-27a-3p` + serum.geNorm.new$`hsa-miR-16-5p` + serum.geNorm.new$`hsa-let-7b-5p` + serum.geNorm.new$`hsa-miR-27b-3p` + serum.geNorm.new$`hsa-miR-29a-3p` + serum.geNorm.new$`hsa-miR-21-5p` + serum.geNorm.new$`hsa-miR-451a` + serum.geNorm.new$`hsa-miR-874-3p`)

step.serum.grade.geNorm = stepAIC(object = fullmodel.serum.geNorm, direction = "backward")

# serum NormFinder
fullmodel.serum.NormFinder = glm(formula = serum.all.original$`Biopsy Grade Group`~ serum.NormFinder.new$`hsa-miR-1246`+ serum.NormFinder.new$`hsa-miR-363-3p`+ serum.NormFinder.new$`hsa-miR-320a` + serum.NormFinder.new$`hsa-miR-125b-5p` + serum.NormFinder.new$`hsa-miR-27a-3p` + serum.NormFinder.new$`hsa-miR-16-5p` + serum.NormFinder.new$`hsa-let-7b-5p` + serum.NormFinder.new$`hsa-miR-27b-3p` + serum.NormFinder.new$`hsa-miR-29a-3p` + serum.NormFinder.new$`hsa-miR-21-5p` + serum.NormFinder.new$`hsa-miR-451a` + serum.NormFinder.new$`hsa-miR-874-3p`)

step.serum.grade.NormFinder = stepAIC(object = fullmodel.serum.NormFinder, direction = "backward")
```

```{r selection 4}
# EV CT mean
fullmodel.EV.CTMean = glm(formula = EV.all.original$`Biopsy Grade Group`~ EV.globalCTMean.new$`hsa-miR-335-5p`+ EV.globalCTMean.new$`hsa-miR-191-5p`+ EV.globalCTMean.new$`hsa-miR-107` + EV.globalCTMean.new$`hsa-miR-130b-3p` + EV.globalCTMean.new$`hsa-miR-221-3p` + EV.globalCTMean.new$`hsa-miR-214-3p` + EV.globalCTMean.new$`hsa-miR-103a-3p` + EV.globalCTMean.new$`hsa-miR-330-3p` + EV.globalCTMean.new$`hsa-miR-30a-5p`+ EV.globalCTMean.new$`hsa-let-7a-5p`)

step.EV.grade.CTMean = stepAIC(object = fullmodel.EV.CTMean, direction = "backward")

# EV geNorm
fullmodel.EV.geNorm = glm(formula = EV.all.original$`Biopsy Grade Group`~ EV.geNorm.new$`hsa-miR-335-5p`+ EV.geNorm.new$`hsa-miR-130b-3p`+ EV.geNorm.new$`hsa-miR-191-5p` + EV.geNorm.new$`hsa-miR-221-3p` + EV.geNorm.new$`hsa-miR-214-3p` + EV.geNorm.new$`hsa-miR-107` + EV.geNorm.new$`hsa-miR-330-3p` + EV.geNorm.new$`hsa-miR-103a-3p`)

step.EV.grade.geNorm = stepAIC(object = fullmodel.EV.geNorm, direction = "backward")

# EV NormFinder
fullmodel.EV.NormFinder = glm(formula = EV.all.original$`Biopsy Grade Group`~ EV.NormFinder.new$`hsa-miR-19b-3p`+ EV.NormFinder.new$`hsa-miR-874-3p`+ EV.NormFinder.new$`hsa-miR-214-3p` + EV.NormFinder.new$`hsa-miR-30a-5p` + EV.NormFinder.new$`hsa-miR-143-3p` + EV.NormFinder.new$`hsa-miR-363-3p` + EV.NormFinder.new$`hsa-miR-451a` + EV.NormFinder.new$`hsa-miR-148a-3p` +  EV.NormFinder.new$`hsa-miR-25-3p` +  EV.NormFinder.new$`hsa-miR-16-5p` +  EV.NormFinder.new$`hsa-miR-222-3p` +  EV.NormFinder.new$`hsa-miR-210-3p` +  EV.NormFinder.new$`hsa-miR-18b-5p`)

step.EV.grade.NormFinder = stepAIC(object = fullmodel.EV.NormFinder, direction = "backward")
```

## Adverse pathology selection
```{r selection ap EV}
fullmodel2 = glm(data = EV.all.original, formula = `Adverse Pathology`~`hsa-let-7a-5p`+`hsa-miR-26b-5p`+`hsa-miR-301a-3p`, family = "binomial")
step.EV.adverse.final = stepAIC(object = fullmodel2, direction = "backward")

## EV CT Mean
fullmodel.EV.CTMean.AP = glm(data = EV.all.original, formula = `Adverse Pathology`~ EV.globalCTMean.new$`hsa-let-7a-5p`+ EV.globalCTMean.new$`hsa-miR-26b-5p`+ EV.globalCTMean.new$`hsa-miR-25-3p` + EV.globalCTMean.new$`hsa-miR-107` + EV.globalCTMean.new$`hsa-miR-103a-3p` + EV.globalCTMean.new$`hsa-miR-199a-5p` + EV.globalCTMean.new$`hsa-miR-301a-3p` + EV.globalCTMean.new$`hsa-miR-363-3p` + EV.globalCTMean.new$`hsa-miR-191-5p` + EV.globalCTMean.new$`hsa-miR-19b-3p` + EV.globalCTMean.new$`hsa-miR-221-3p` + EV.globalCTMean.new$`hsa-miR-27b-3p` + EV.globalCTMean.new$`hsa-miR-451a` + EV.globalCTMean.new$`hsa-miR-374a-5p` + EV.globalCTMean.new$`hsa-miR-16-5p`,family = "binomial")

step.EV.adverse.CTMean = stepAIC(object = fullmodel.EV.CTMean.AP, direction = "backward")

# EV geNorm
fullmodel.EV.geNorm.AP = glm(data = EV.all.original, formula = `Adverse Pathology`~ EV.geNorm.new$`hsa-miR-25-3p`+ EV.geNorm.new$`hsa-miR-199a-5p`+ EV.geNorm.new$`hsa-miR-30c-5p` + EV.geNorm.new$`hsa-let-7a-5p` + EV.geNorm.new$`hsa-miR-191-5p` + EV.geNorm.new$`hsa-miR-27b-3p` + EV.geNorm.new$`hsa-miR-363-3p` + EV.geNorm.new$`hsa-miR-26b-5p` + EV.geNorm.new$`hsa-miR-221-3p` + EV.geNorm.new$`hsa-miR-16-5p` + EV.geNorm.new$`hsa-miR-19b-3p` + EV.geNorm.new$`hsa-miR-107` + EV.geNorm.new$`hsa-miR-27a-3p` + EV.geNorm.new$`hsa-miR-301a-3p` + EV.geNorm.new$`hsa-miR-451a` + EV.geNorm.new$`hsa-miR-199a-3p` + EV.geNorm.new$`hsa-miR-103a-3p` + EV.geNorm.new$`hsa-miR-23a-3p` + EV.geNorm.new$`hsa-miR-24-3p` + EV.geNorm.new$`hsa-miR-141-3`,family = "binomial")

step.EV.adverse.geNorm = stepAIC(object = fullmodel.EV.geNorm.AP, direction = "backward")

# EV NormFinder
fullmodel.EV.NormFinder.AP = glm(data = EV.all.original, formula = `Adverse Pathology`~ EV.NormFinder.new$`hsa-miR-199a-5p`+ EV.NormFinder.new$`hsa-miR-30c-5p`+ EV.NormFinder.new$`hsa-miR-221-3p` + EV.NormFinder.new$`hsa-miR-27b-3p` + EV.NormFinder.new$`hsa-let-7a-5p` + EV.NormFinder.new$`hsa-miR-25-3p` + EV.NormFinder.new$`hsa-miR-191-5p` + EV.NormFinder.new$`hsa-miR-363-3p` + EV.NormFinder.new$`hsa-miR-19b-3p` + EV.NormFinder.new$`hsa-miR-107` + EV.NormFinder.new$`hsa-miR-451a` + EV.NormFinder.new$`hsa-miR-16-5p` + EV.NormFinder.new$`hsa-miR-199a-3p` + EV.NormFinder.new$`hsa-miR-103a-3p` + EV.NormFinder.new$`hsa-miR-27a-3p`,family = "binomial")

step.EV.adverse.NormFinder = stepAIC(object = fullmodel.EV.NormFinder.AP, direction = "backward")

```

```{r ap serum selection}
# serum CT Mean
fullmodel.serum.ctmean.ap = glm(data = serum.all.original, formula = `Adverse Pathology`~ serum.globalCTMean.new$`hsa-miR-1246`, family = "binomial")
step.EV.adverse.final = stepAIC(object = fullmodel.serum.ctmean.ap, direction = "backward")

# serum geNorm
fullmodel.serum.geNorm.ap = glm(data = serum.all.original, formula = `Adverse Pathology`~ serum.geNorm.new$`hsa-miR-1246` + serum.geNorm.new$`hsa-miR-100-5p` + serum.geNorm.new$`hsa-miR-574-3p`, family = "binomial")
step.EV.adverse.final = stepAIC(object = fullmodel.serum.geNorm.ap, direction = "backward")

# serum NormFinder
fullmodel.serum.NormFinder.ap = glm(data = serum.all.original, formula = `Adverse Pathology`~ serum.NormFinder.new$`hsa-miR-100-5p` + serum.NormFinder.new$`hsa-miR-574-3p` + serum.NormFinder.new$`hsa-miR-221-3p` + serum.NormFinder.new$`hsa-miR-1246`, family = "binomial")
step.EV.adverse.final = stepAIC(object = fullmodel.serum.NormFinder.ap, direction = "backward")
```

